import os
import unittest
from pathlib import Path


ROOT = Path(__file__).parents[1]


class AddressBarNavigationContractTests(unittest.TestCase):
    """A typed domain must never depend on the silent bfsb:// action channel."""

    def setUp(self):
        self.template = (ROOT / "bfsb/templates/bfsb_combined.html").read_text(encoding="utf-8")
        self.server = (ROOT / "bfsb/core/server.py").read_text(encoding="utf-8")

    def test_address_bar_has_a_direct_navigation_fallback(self):
        self.assertIn("function navigateFromAddressBar", self.template)
        self.assertIn("window.location.replace(url)", self.template)
        self.assertIn("navigateFromAddressBar(direct)", self.template)

    def test_action_failures_are_logged_not_swallowed(self):
        self.assertNotIn("fetch(url).catch(function() {});", self.template)
        self.assertIn("action channel failed", self.template)

    def test_nav_buttons_prefer_local_http_routes(self):
        for route in ("/_bfsb/reload", "/_bfsb/goBack", "/_bfsb/goForward"):
            self.assertIn(route, self.template)
            self.assertIn(route, self.server)
        self.assertIn("function httpNavAction", self.template)

    def test_new_tab_rejects_non_http_schemes(self):
        self.assertIn("main._safe_action_target(url)", self.server)
        self.assertIn("main._safe_action_target(target)", self.server)


class PhaseContractTests(unittest.TestCase):
    def test_phase2_progress_contract(self):
        server = (ROOT / "bfsb/core/server.py").read_text(encoding="utf-8")
        main = (ROOT / "bfsb/ui/main_window.py").read_text(encoding="utf-8")
        template = (ROOT / "bfsb/templates/bfsb_combined.html").read_text(encoding="utf-8")
        self.assertIn("/api/search/progress", server)
        self.assertIn("format", server)
        self.assertIn("EventSource", template)
        self.assertIn("engine_done", template)
        self.assertIn("runSearch", template)
        self.assertIn("progressHideTimer", template)
        self.assertIn("activeSearch.rendered", template)
        self.assertIn("btn-back", template)
        self.assertIn("__bfsbSetNavState", template)
        self.assertIn("bfsbLocalHistoryManaged", template)
        self.assertIn("bfsbHistoryIndex", template)
        self.assertIn("hashchange", template)
        self.assertIn("showCategoryFromHash", template)
        self.assertIn("BFSB Category", template)
        self.assertIn("_sync_nav_state", main)
        self.assertNotIn("setTimeout(hideProgress, 1300)", template)

    def test_phase3_tab_contract(self):
        main = (ROOT / "bfsb/ui/main_window.py").read_text(encoding="utf-8")
        template = (ROOT / "bfsb/templates/bfsb_combined.html").read_text(encoding="utf-8")
        self.assertIn("def reorder_tabs", main)
        self.assertIn("reorderTabs", template)
        self.assertIn("/api/ui/switchTab", template)
        self.assertIn("handle_api_ui_switch_tab", (ROOT / "bfsb/core/server.py").read_text(encoding="utf-8"))
        self.assertIn("auxclick", template)
        self.assertIn("openInNewTab:false", template)
        self.assertIn("target_view=view", main)
        self.assertIn("_view_titles", main)
        self.assertNotIn("page().title() if", main)
        self.assertIn("http://127.0.0.1:8889", main)
        webengine = (ROOT / "bfsb/core/webengine.py").read_text(encoding="utf-8")
        self.assertIn('new_tab(\n                "about:blank"', webengine)
        self.assertIn('private=bool(getattr(self, "_private", False))', webengine)
        self.assertNotIn("sync_timer.start(500)", webengine)

    def test_phase4_chrome_contract(self):
        chrome = (ROOT / "bfsb/ui/browser_chrome.py").read_text(encoding="utf-8")
        main = (ROOT / "bfsb/ui/main_window.py").read_text(encoding="utf-8")
        self.assertNotIn("sidebar_toggle", chrome)
        self.assertNotIn("btn_sidebar", chrome)
        self.assertIn("class NativeTab(QToolButton)", chrome)
        self.assertNotIn("def mousePressEvent", chrome)
        self.assertNotIn("menu_clicked", chrome)
        self.assertIn("ExternalSideOverlay", main)
        self.assertIn("content_layout.addWidget(self._side_overlay)", main)
        self.assertIn("right_layout.addWidget(self._chrome)", main)
        self.assertIn("right_layout.addWidget(self._view_content, 1)", main)
        self.assertIn("CategoryPopup", main)
        self.assertIn("open_panel(panel)", main)
        self.assertNotIn("view.setUrl(QUrl(target))", main)
        self.assertIn("QShortcut", main)
        popup = (ROOT / "bfsb/ui/category_popup.py").read_text(encoding="utf-8")
        overlay = (ROOT / "bfsb/ui/side_overlay.py").read_text(encoding="utf-8")
        self.assertIn("self.open_overlay()", overlay)
        self.assertIn("panel_layout.setContentsMargins(12, 18, 12, 18)", overlay)
        self.assertIn("panel_layout.setSpacing(0)", overlay)
        self.assertIn("setFixedHeight(38)", overlay)
        self.assertIn("def set_collapsed", overlay)
        self.assertIn("self._brand_text", overlay)
        self.assertIn("QPushButton:focus", overlay)
        self.assertIn("setFocusPolicy(Qt.FocusPolicy.NoFocus)", overlay)
        self.assertNotIn("self.setFocus(Qt.FocusReason.OtherFocusReason)", overlay)
        for label in ("Home", "Bookmarks", "History", "Downloads", "Safe Browsing", "Passwords", "Settings"):
            self.assertIn(label, overlay)
        for label in ("New tab", "Quit BFSB", "Adblocker: On"):
            self.assertNotIn(label, overlay)
        self.assertIn("close_popup", popup)
        self.assertNotIn('"home": "Home"', popup)
        self.assertNotIn('"about": "About BFSB"', popup)
        self.assertIn("categoryPopupRailButton", popup)
        self.assertIn("urlChanged.connect", popup)
        self.assertIn("mousePressEvent", popup)
        self.assertIn("setCachePath", (ROOT / "bfsb/core/webengine.py").read_text(encoding="utf-8"))
        template = (ROOT / "bfsb/templates/bfsb_combined.html").read_text(encoding="utf-8")
        self.assertIn("__bfsbSetSidebarCollapsed", template)
        self.assertIn("localStorage.getItem('bfsb-sidebar-collapsed')", template)
        self.assertIn("sidebarcollapsed", main)
        self.assertIn("_sidebar_state_initialized", main)
        self.assertIn("sidebar-state.json", main)
        self.assertIn("_save_sidebar_state", main)
        self.assertIn("_BOOKMARK_PATH", chrome)
        self.assertIn("M6 3h12", template)
        self.assertIn("bfsb_icon.png", template)
        self.assertNotIn('<rect width="256" height="256"', (ROOT / "bfsb_icon.svg").read_text(encoding="utf-8"))
        self.assertIn("parents[2] / \"bfsb_icon.png\"", overlay)
        self.assertNotIn("templates\" / \"static\" / \"bfsb_icon.png", overlay)
        self.assertIn("background: transparent", template)
        self.assertIn("view-about", template)
        self.assertIn("setFixedWidth(190)", chrome)
        self.assertIn("self._tabs_layout.addWidget(self.new_tab_btn)", chrome)
        self.assertIn("__bfsbRenderTabs", main)
        self.assertIn("window.__bfsbRenderTabs", template)
        self.assertNotIn("strip.innerHTML = html", main)
        self.assertIn("htmlUiAction('/api/ui/newTab'", template)
        self.assertIn("htmlUiAction(\n          '/api/ui/closeTab'", template)
        self.assertIn("window.refreshHomeBookmarks = refreshHomeBookmarks", template)
        self.assertIn("#homeBookmarks .bookmark')", template)
        self.assertNotIn("#homeBookmarks .bookmarks')", template)
        self.assertIn("min-height: 18px", chrome)
        self.assertIn("setFixedSize(18, 18)", chrome)
        self.assertIn("WA_StyledBackground", chrome)
        self.assertIn("--tab-width: 190px", template)
        self.assertIn(".side-logo .mark:hover", template)
        self.assertIn("logo-collapse", template)
        self.assertNotIn("sidebar-toggle", template)
        self.assertIn("sidebarLogo", template)
        self.assertIn("MouseButtonPress", overlay)
        self.assertIn("def _fallback_tab_title", main)
        self.assertIn("YouTube Shorts", main)
        self.assertIn("min-height: 52px", template)
        self.assertNotIn("translateX(-114px)", template)
        self.assertNotIn("bfsb-native-tabs", template)
        self.assertNotIn("viewport().installEventFilter", chrome)
        self.assertNotIn("set_local_page", main)
        self.assertNotIn("setStylesheet", chrome)
        self.assertNotIn("QFrame.Shadow.NoShadow", chrome)
        self.assertIn("RoundedAddressPill", chrome)
        self.assertIn("QFrame#addressPill", chrome)
        self.assertIn("border: none", chrome)
        self.assertIn("stroke: #e8eaf2", template)
        self.assertNotIn("transition: width .25s ease", template)
        self.assertNotIn("transition: margin-left .25s ease", template)

    def test_phase5_proxy_contract(self):
        addon = (ROOT / "bfsb/core/proxy_addon.py").read_text(encoding="utf-8")
        bootstrap = (ROOT / "bfsb/core/proxy_bootstrap.py").read_text(encoding="utf-8")
        main = (ROOT / "bfsb/main.py").read_text(encoding="utf-8")
        self.assertIn("http.Response.make(200", addon)
        self.assertIn("responseheaders", addon)
        self.assertIn("flow.response.stream = True", addon)
        self.assertIn("ALLOW_HOSTS", bootstrap)
        self.assertNotIn("ssl_insecure=true", bootstrap)
        self.assertNotIn("ssl_insecure=true", (ROOT / "bfsb/core/proxy_manager.py").read_text(encoding="utf-8"))
        self.assertIn("BFSB_TEST", main)
        self.assertNotIn("ContentSecurityPolicyIgnored", main)
        self.assertIn("info.redirect(QUrl(rewritten))", (ROOT / "bfsb/core/webengine.py").read_text(encoding="utf-8"))
        self.assertIn("BFSB_USE_PRIVACY_FRONTENDS", (ROOT / "bfsb/core/webengine.py").read_text(encoding="utf-8"))
        launcher = (ROOT / "bfsb_launcher.sh").read_text(encoding="utf-8")
        self.assertIn("start_searxng_async", launcher)
        self.assertIn("terminate_tree", launcher)
        self.assertIn("stop_recorded_proxy", launcher)
        server = (ROOT / "bfsb/core/server.py").read_text(encoding="utf-8")
        self.assertIn("/api/ui/closeTab", server)
        self.assertIn("handle_api_close_tab", server)
        passwords = (ROOT / "bfsb/core/passwords.py").read_text(encoding="utf-8")
        self.assertIn("class PasswordVault", passwords)
        self.assertIn("VaultStore", passwords)
        self.assertIn("VaultKeyProvider", passwords)
        vault = (ROOT / "bfsb/core/secure_vault.py").read_text(encoding="utf-8")
        self.assertIn("PRAGMA secure_delete=ON", vault)
        self.assertIn("VAULT_VERSION = 2", vault)
        config = (ROOT / "bfsb/core/config.py").read_text(encoding="utf-8")
        self.assertIn("VAULT_DB", config)
        self.assertIn("VAULT_KEY", config)
        profile_code = (ROOT / "bfsb/core/webengine.py").read_text(encoding="utf-8")
        self.assertIn("setCookieFilter", profile_code)
        self.assertIn("PASSWORD_CAPTURE_SCRIPT", profile_code)
        self.assertIn("_is_youtube_age_gate_bypass", profile_code)
        self.assertIn("BFSB_YOUTUBE_SAFE_MODE", profile_code)
        main_window = (ROOT / "bfsb/ui/main_window.py").read_text(encoding="utf-8")
        self.assertIn("private: bool = False", main_window)
        self.assertIn("Private tab", main_window)

    def test_searxng_lifecycle_contract(self):
        checkup_path = ROOT / "bfsb_checkup.sh"
        checkup = checkup_path.read_text(encoding="utf-8")
        self.assertTrue(os.access(checkup_path, os.X_OK))
        self.assertIn("REPLACE_EXISTING", checkup)
        self.assertIn("cleanup_stale_searxng", checkup)
        self.assertIn("owner_is_active", checkup)
        self.assertNotIn("pkill -KILL", checkup)
        self.assertNotIn("pkill -TERM -f", checkup)
        self.assertIn("BFSB_BROWSER_PID_FILE", checkup)
        self.assertIn("stop_recorded_process", checkup)
        self.assertNotIn("stop_sarxng", checkup)
        self.assertIn("exit 0", checkup)
        for filename in ("bfsb_launcher.sh", "bfsb_launcher.podman.sh"):
            launcher_path = ROOT / filename
            launcher = launcher_path.read_text(encoding="utf-8")
            self.assertTrue(os.access(launcher_path, os.X_OK))
            self.assertIn('"$BFSB_CHECKUP" --replace', launcher)
            self.assertLess(launcher.index('"$BFSB_CHECKUP" --replace'), launcher.index("start_searxng_async"))
            self.assertNotIn("reset_stale_searxng", launcher)
            self.assertNotIn("stop_sarxng", launcher)
            self.assertNotIn("pkill -KILL -f '[b]fsb.main'", launcher)
            self.assertIn("BFSB_SEARXNG_OWNER_FILE", launcher)
            self.assertIn('current_owner" = "$BFSB_LAUNCHER_ID"', launcher)
            self.assertIn("claim_launcher_lock", launcher)
            self.assertIn("BFSB_CLEANUP_SERVICES", launcher)
            self.assertIn("shutdown_handler", launcher)
            self.assertIn("browser did not exit cleanly", launcher)
            self.assertIn("9>&-", launcher)
        legacy_launcher = (ROOT / "launch.sh").read_text(encoding="utf-8")
        self.assertIn('"$SCRIPT_DIR/bfsb_checkup.sh" --replace', legacy_launcher)


if __name__ == "__main__":
    unittest.main()
